site:
  title: Training
  url: http://training.rezaulhasan.me
  start_page: java::index.adoc
  keys:
    google_analytics: 'UA-164685388-1'
content:
  sources:
    - url: https://github.com/xomidar/java-conventions.git
      branches: HEAD
      start_path: docs
asciidoc:
  attributes:
    max-include-depth: 10
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    toc: ~
    xrefstyle: short
    hide-uri-scheme: ''
    table-caption: ~
    page-toclevels: '3'
    tabs: tabs
    source-language: asciidoc@
  extensions:
    - ./lib/tabs-block.js
    - ./lib/swagger-ui-block-macro.js
    - ./lib/source-url-include-processor.js
    - ./lib/json-config-ui-block-macro.js
    - ./lib/inline-man-macro.js
    - ./lib/multirow-table-head-tree-processor.js
ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: https://github.com/couchbase/docs-ui-sandbox/releases/download/prod-94/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./public
  clean: true
  destinations:
    - provider: fs
      path: ./
