[#directory-structure]
== Structure

During project generation Maven and Gradle generates their default directory structure.
It doesn't matter you have created from scratch, or generated the java project both tools expects and uses their default directory structure for the build process.
If the default directory convention doesn't match your needs you can still explicitly configure.

[{tabs}]
====
Gradle::
+
--
[IMPORTANT]
Gradle https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_project_layout[directory convention implicitly, window="_blank"] configured by plugins.
You can change this default directory by https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html[SourceSet, window="_blank"] block.

*Gradle default directory structure*

image::build-tools/gradle-directory-structure.svg[Gradle,70%]

* `settings.gradle` file is optional and only required in root project for multi module projects.

* `build` directory is generated output directory.

*Override default configuration*

.build.gradle
[source,groovy]
----
include::beginner:example$build-tools/structure/directory-configuration.gradle[]
----
<1> Explicitly directory structure configuration by `sourceSets` block.

*Sample build.gradle file generated by IntelliJ IDEA*

.build.gradle
[source,groovy]
----
include::beginner:example$build-tools/structure/example-intellij.gradle[]
----

--

Maven::
+
--
[IMPORTANT]
Maven http://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html[directory convention implicitly, window="_blank"] inherit from http://maven.apache.org/ref/current/maven-model-builder/super-pom.html[Super POM, window="_blank"].
You can change this default directory inside http://maven.apache.org/ref/current/maven-model/maven.html#class_build[<build>, window="_blank"] element.

*Maven default directory structure*

image::build-tools/maven-directory-structure.svg[Maveb,70%]

* `target` directory is generated output directory.

*Override default configuration*

.pom.xml
[source,xml]
----
include::beginner:example$build-tools/structure/directory-configuration.xml[]
----
<1> Explicitly directory structure configuration inside `<build>` element.

*Sample pom.xml file generated by IntelliJ IDEA*

.pom.xml
[source,xml]
----
include::beginner:example$build-tools/structure/example-intellij.xml[]
----

--
====
